# Makefile
ARDUINO_DIR = /Applications/Arduino.app/Contents/Java
ARMK_DIR = ${HOME}/Desktop/Coding/Projects/arduino/Arduino-Makefile/

include $(ARMK_DIR)/Arduino.mk

DEVICE_PATH = /dev/cu.usbmodem1411
